### ISSUE TITLE
Communicate system tilt and azimuth to COMSOL

### ISSUE THREAD

**Issue by mdeceglie** [NREL/pv_tomcat#1]
This issue is migrated from enterprise github, where @silverman made the following comments:

The COMSOL model doesn't use azimuth for anything, so it's just about tilt. There are multiple options:

1. Create a new input file 'tilt.csv' or something and have COMSOL use it in place. Advantage: Like the time-series input file, the simulation will just refer to the local tilt file. Disadvantage: We'd have to implement this as an off-label use of COMSOL's interpolation function, which smells because we'd be 'interpolating' a one-row file and every reference to tilt would have to be tilt(0). Disregard previous comments about variable tilt being easy to implement as a time series; that's more complicated than we can do under this project.

2. Reintroduce the concept of the .java template file and have our Python accessory programs insert tilt into the template to make a ready-to-compile model file. Disadvantage: User has to learn how to compile COMSOL files, which is otherwise not necessary.

3. Move _all_ of the FEM's parameters, including thicknesses, thermal conductivities, and so on, into a parameters file and have the Python program update tilt there. Disadvantage: User has to manually import this parameters file if it changes.

4. Leave tilt blank in the COMSOL file so simulation won't run unless the user enters it manually. Disadvantage: User has to enter tilt twice.

There may be others. What do you think?

If we're optimizing for internal use, the winner is 2.

**Comment by silverman** [comment]
I put tilt all by itself in a text file and wrote the java to read it.
